# Generated by Django 3.1.4 on 2021-01-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="status", options={"ordering": ("-pk",)},),
        migrations.AddField(
            model_name="status",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
